### PR TITLE
Pharma - Change KAM Painkillers to CWMP

### LINKED ISSUE #546: ACE/KAM Painkillers config conflict
**Description:**
Ace recently added their own painkillers, and its uses the config name 'PainKillers' in the Ace Medical Treatment cfg's.
Kat also uses the same config name for its painkillers.

**Steps to reproduce:**
1. Load into Ace virtual arsenal.
2. Add "ace_painkillers" to your inventory
3. Try to use said painkillers on your head.
4.  No option appears.

**Where did the issue occur?**
- Self-Hosted Multiplayer  / Virtual Arsenal

**Additional information:**
ACE_Medical_Treatment_Actions
[Ace Painkillers -  Config](https://github.com/acemod/ACE3/blob/565d64d50ed775dafbbefafe05457577e955712b/addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp#L145)
[KAM Painkillers -  Config](https://github.com/KAT-Advanced-Medical/KAM/blob/e7196ae992eb2e4e2d8135933a9d0e8994d464bf/addons/pharma/ACE_Medical_Treatment_Actions.hpp#L43)
ACE_Medical_Treatment >> Medication
[Ace Painkillers - Config](https://github.com/acemod/ACE3/blob/565d64d50ed775dafbbefafe05457577e955712b/addons/medical_treatment/ACE_Medical_Treatment.hpp#L610C15-L610C26)
[KAM Painkillers - Config](https://github.com/KAT-Advanced-Medical/KAM/blob/e7196ae992eb2e4e2d8135933a9d0e8994d464bf/addons/pharma/ACE_Medical_Treatment.hpp#L175)

The items do not conflict with each other, only the medical configs.

### PR DESCRIPTION
**Pull request by Apricot-ale**
**When merged this pull request will:**
- _Fix https://github.com/KAT-Advanced-Medical/KAM/issues/546 problem._
- _Rename whole of (KAT) Painkillers thing (except item class name) to CWMP (from [TCCC 14.3](https://tccc.org.ua/en/guide/combat-wound-medication-pill-pack)) and item stringtable to Combat-Pill-Pack (from  [DD 1380 TCCC CASUALTY CARD](https://learning-media.allogy.com/api/v1/pdf/eb6c36b5-edbf-4e68-ae47-7a6e6536c6e7/contents))_
- _Max "ammo" count is now 10->4, weight is 1->0.5 (Guide need to change)_

New icon;
icon_painkillers
New icon with higher resolutions (you know where it come from...)
when 64x64, almost text are can't read and texture not detailed so it's will be ok
icon_painkillers_256

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

File: addons/pharma/XEH_PREP.hpp [hunk 1]
```diff
@@ -36,7 +36,7 @@ PREP(treatmentAdvanced_MorphineLocal);
 PREP(treatmentAdvanced_NalbuphineLocal);
 PREP(treatmentAdvanced_Naloxone);
 PREP(treatmentAdvanced_NaloxoneLocal);
-PREP(treatmentAdvanced_Painkillers);
+PREP(treatmentAdvanced_KAT_Painkillers);
```
Comment (MiszczuZPolski) [inline addons/pharma/XEH_PREP.hpp]: There is no need to add KAT here

**Review by MiszczuZPolski — CHANGES_REQUESTED** [review]

**Review by MiszczuZPolski — APPROVED** [review]
